DROP TABLE IF EXISTS friends, film_likes, film_genre, genres, films, rating_mpa, users;

CREATE TABLE users
(
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(100),
    login     VARCHAR(50),
    email     VARCHAR(50),
    birthday  DATE
);

CREATE TABLE rating_mpa
(
    mpa_id          INT PRIMARY KEY,
    mpa_name        VARCHAR(10),
    mpa_description VARCHAR(100)
);

CREATE TABLE films
(
    film_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name     VARCHAR(100),
    description   VARCHAR(200),
    release_date  DATE,
    duration      INT,
    rating_mpa_id INT,
    CONSTRAINT rating_mpa FOREIGN KEY (rating_mpa_id) REFERENCES rating_mpa (mpa_id)
);

CREATE TABLE genres
(
    genre_id   INT PRIMARY KEY,
    genre_name VARCHAR(20)
);

CREATE TABLE film_genre
(
    film_id INT REFERENCES films (film_id),
    genre_id INT REFERENCES genres (genre_id),
    primary key (film_id, genre_id)

);

CREATE TABLE film_likes
(
    film_id INT REFERENCES films (film_id),
    user_id INT REFERENCES users (user_id),
    primary key (film_id, user_id)
);

CREATE TABLE friends
(
    user_id INT REFERENCES users (user_id),
    friend_id INT REFERENCES users (user_id),
    primary key (user_id, friend_id)

);




